### ISSUE TITLE
bug Healing can kill

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#197]
Wounds to the abdomen have rendered the Actor "unconscious".  (Maybe the actor should really be "dead" at this point?)
![image](https://user-images.githubusercontent.com/3959760/155793974-0629f2eb-7c3d-4056-9133-53a8dab86cde.png)

About to heal 2HP from one of the wounds.
![image](https://user-images.githubusercontent.com/3959760/155794271-64829805-6655-475b-aa7c-7810f4772885.png)

After healing actor is "dead".  
![image](https://user-images.githubusercontent.com/3959760/155794414-1bf166f0-0664-4e83-a835-371a359b2e0d.png)

Should the Actor have been dead originally because of the Abdomen being at  -7/5? And stayed dead because the Abdomen was at -5/5 after the healing?

Or if "unconscious" is correct at Abdomen -7/5 and total HP 1/13, then the actor should simply be "wounded" after healing 2 HP.

As a side note, if the abdomen is healed fully the legs remain useless.

![image](https://user-images.githubusercontent.com/3959760/155796161-b1a1085a-b77e-4a49-8113-3b34e86b6c93.png)

**Comment by wake42** [comment]
at -7/5 the actor should not be dead, just unconscious

**Comment by Moonpile** [comment]
After merging in the changes to fix the status and the fix to ensure that a wound radio button is always selected, I'm unable to reproduce this now.

**Comment by wake42** [comment]
I tested a bit as well and what seems to happens is that the actor dies, that is recorded in `actorHealthImpact` on the hit location that makes the actor die. When you heal the wounds the `actorHealthImpact: dead` is removed when the HP of that hitlocation is > 0.

Closing this issue since it seems like a minor issue (assuming "dead" should be removed when total HP is > 0).
