### ISSUE TITLE
Create Homeland Item

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#202]
### _Why:_ Is your feature request related to a problem?
To make creating an extensible character wizard #101 possible we need a way of storing different homelands and their impact on characters. Adding a homeland item would make it easy to include a set of homelands in a compendium

### _What:_ Describe the solution you'd like
The homeland item should contain
- Description (large text) _- should this be a link to a journalEntry to keep the data size embedded in an actor down?_
- Cultural Stereotype (large text) _- link to journalEntry?_
- Common Cults (list of references to "Cult" items by rqgId #199)
- Suggested Occupations (list of references to "Occupation" items by rqgId #199)
- Passions (list of references to "Passion" items by rqgId #199) 
- List of presets for Town / Home Area dropdown datalist
- Characteristics modifiers (SIZ / DEX +-)
- Map of cultural skill bonuses (rqgId -> modifier). _For weapon skills this should be checked when learning (adding) a new weapon skill._

If we're making a "Homeland" item type do we just have a field on the Actor to hold a Homeland? Then just render it on the background tab, replacing some existing fields there. Also need to give a way of copying a cult over to the Actor, and copying over the base passions.
 
### Additional context
How should we handle dragging a homeland to an actor that already has a homeland item?

### Related to
- [ ] #203

### Blocks
- [ ] #101

### Blocked by
- [x] #199

**Comment by Moonpile** [comment]
> * Common Cults (list of references to "Cult" items by rqgId [System specific item id #199](https://github.com/sun-dragon-cult/fvtt-system-rqg/issues/199))
> * Suggested Occupations (list of references to "Occupation" items by rqgId [System specific item id #199](https://github.com/sun-dragon-cult/fvtt-system-rqg/issues/199))
> * Passions (list of references to "Passion" items by rqgId [System specific item id #199](https://github.com/sun-dragon-cult/fvtt-system-rqg/issues/199))

I'm envisioning dragging these on to the Occupation sheet to configure it (like from the items sidebar or compendium), and later, being able to drag them onto the actor to choose one or more of them.

**Comment by Moonpile** [comment]
> How should we handle dragging a homeland to an actor that already has a homeland item?

Allow more than one homeland? Like I was born in Sartar but moved to Pavis?  I can't think of any downside to this as the Homeland is purely informational, with the exception of cults, occupation, or passions that you *might have chosen* from it.  You don't even have to have chosen them from here.  You could have gotten them from compendia or somewhere else if you wanted.  Maybe make a button to "apply  the characteristic modifiers" or "apply skill bonuses".  I think it's kind of up to the player to only do that once, or perhaps we can set a flag on the actor that disables those buttons.

As for those I suppose we just add the characteristic bonus directly to the characteristic and we add the skill bonus to either the base chance or the learned chance.  Unless there's a reason, I would put it on base chance since being somewhat better at riding horses because of your culture has about the same reasoning as the base chance does in the first place.

**Comment by Moonpile** [comment]
> * List of presets for Town / Home Area dropdown datalist

Where would we store this information?  Seems like a bit much for a setting.  Maybe in a journal item so that GMs can more easily expand or replace it?

Should tribe and clan be in here?

- Settlement (town/village/farmstead)
- Tribe
- Clan

And while these have a loose association someone from Colymar tribe is most likely to be from Colymar lands but could be living in Jonstown or Boldhome or somewhere else.

**Comment by wake42** [comment]
> > * Common Cults (list of references to "Cult" items by rqgId [System specific item id #199](https://github.com/sun-dragon-cult/fvtt-system-rqg/issues/199))
> > * Suggested Occupations (list of references to "Occupation" items by rqgId [System specific item id #199](https://github.com/sun-dragon-cult/fvtt-system-rqg/issues/199))
> > * Passions (list of references to "Passion" items by rqgId [System specific item id #199](https://github.com/sun-dragon-cult/fvtt-system-rqg/issues/199))
> 
> I'm envisioning dragging these on to the Occupation sheet to configure it (like from the items sidebar or compendium), and later, being able to drag them onto the actor to choose one or more of them.

Dragging these things to the Homeland Sheet to create lists of rqid links sounds like a good idea. 

What should happen when you drag the homeland item to the actor? Should you be presented with some kind of dialog where you can choose which cult you want to join? And what occupation you want to have? How would you handle if you wanted to choose something else?

**Comment by wake42** [comment]
> > * List of presets for Town / Home Area dropdown datalist
> 
> Where would we store this information? Seems like a bit much for a setting. Maybe in a journal item so that GMs can more easily expand or replace it?

How would a journal entry store a list of towns etc? Take each line as an option maybe? Also that would make the data more brittle since the homeland item then needs an accompanying journal entry that has a 1:1 relationship. A list on the homeland item would be better I think.

> 
> Should tribe and clan be in here?
> 
> * Settlement (town/village/farmstead)
> * Tribe
> * Clan
> 
> And while these have a loose association someone from Colymar tribe is most likely to be from Colymar lands but could be living in Jonstown or Boldhome or somewhere else.

I think that would be quite a lot of info - if there is something like that, then maybe, but it will always be pretty incomplete I think. Maybe better to not have it?
