### ISSUE TITLE
Include the wiki items

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#260]
### Include the wiki items etc.
- [ ] Homelands https://rqwiki.chaosium.com/adventurers/homeland.html
- [ ] Occupations https://rqwiki.chaosium.com/adventurers/occupation.html
- [x] Characteristics and Runes https://rqwiki.chaosium.com/adventurers/characteristics-and-runes.html
- [x] Cults https://rqwiki.chaosium.com/adventurers/cult.html
- [x] Gear https://rqwiki.chaosium.com/equipment/general.html
- [x] Weapons 
- https://rqwiki.chaosium.com/equipment/melee-weapons.html
- https://rqwiki.chaosium.com/equipment/missile-weapons.html
- https://rqwiki.chaosium.com/equipment/shields.html#shield-table
- [x] Armor https://rqwiki.chaosium.com/equipment/armor.html#armor-table
- [x] Bestiary https://rqwiki.chaosium.com/bestiary/
- [x] Hit Locations for Bestiary
### Is blocked by
- [x] #261

**Comment by Moonpile** [comment]
@ChaosiumNeil, I put my questions here so that they're with the issue.

The wiki does not have ENC values for anything. https://rqwiki.chaosium.com/equipment/general.html

Several of the items encompass a group of items, so I've "expanded" them just a bit to make it clear that there's a wealth of items to come in the RQG module and the W&E module.

The following list is the "grouping" from the wiki with the description text, followed by the items I "expanded" the group into.  The numbers are the ENC I assigned them.

I did not include services like "guard", "inn", "herald", "labor", "research", and "sacrifice".

Cloak: 	Anywhere from 5 C for woven grass to 5 L for fur or hide.
0.5 Grass Cloak
0.5 Wool Winter Cloak

Clothes: 2 L for a set of rough cotton garments, up to 20 L for silk finery.
This encompasses even more detailed items.  
0.5 Cotton Clothing
0.5 Wool Clothing

Dress: 1 L for a plain drape, up to 35 L for fashion from Esrolia.
0.5 Esrolian Dress
0.5 Plain Hide Dress

Drink: A bowl of mead or wine runs 1 C, and ale is much cheaper. The famed clearwine (from Clearwine) runs 4 C per bowl. A whole amphora of passable mead or wine costs around 8 L and contains 75 bowls or mugs of booze.
0.2 Two Cups of Ale (I did two cups because the price is half a Clack per cup, and it was easier to just have whole Clacks, and because a cup of ale is best enjoyed with a friend)
0.1 Bowl of Clearwine
0.1 Horn of Mead

Food: A hearty midday meal consisting of fried or flatbread, cooked meat (beef, chicken, pork, fish, etc.), a vegetable soup, fruit, and wine runs about 6 C.
0.2 Bowl of Meat Stew

Horse: 65 L for a riding horse, twice that for a warhorse.
N/A(?) Galana (pony)  (which I chose as the most common horse in Dragon Pass and for "flavor")

Jewelry: Anywhere from 1 L for a simple bronze ring to 3,000 L for a weighty, jeweled, golden bracelet.
0.0 Simple Bronze Ring
0.0 Beaded Gold Necklace

Lamp: Only 2 L for a small clay oil lamp and enough oil to burn for hours.
0.5 Lamp

Music Instruments: These can range from 2 C for some cheap reed pipes or gourd rattles to 25 L for a fancy lute or lyre.
1.0 Drum
3.0 Kithara

Riding Gear: 2 L for basic rope tack and a blanket saddle, up to 20 L for fine leather- and metal-working.
Interestingly Tack doesn't seem to be in W&E but is briefly mentioned in RQG on p 411. Tack is a term for all the gear.  I think RQG and the wiki probably meant "bridle" or "harness". I went with "bridle".
2.0 Saddle Blanket
1.5 Bridle
5.0 Saddle

Tools: 	A cheap stone hammer might be 5 C, 15 meters (16½ yards) of rope.
0.5 Stone Hammer
2.0 Rope, 15m
