### ISSUE TITLE
Change handlebar helpers to use uuid instead of actor/token id

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#383]
Even tokens have uuids `Scene.Ox88UZhbjvAumAtF.Token.LdjLeJ3RcqVCWgXZ` and `fromUuidSync()` is not async so it's possible to use in a handlebar helper. 
The handlebar helpers to change are `{{itemname }}` `{{skillname }}` `{{skillchance }}` `{{experiencedclass }}` `{{quantity }}` 

This will fix #456 where the problem is that you won't find the actor of an unlinked token with the handlebars helper `skillchance` using only `actorId` & `tokenId` so a new actor is created which in turn runs the prepareData cycle that will take a really long time.

**Comment by Moonpile** [comment]
I'm trying to do this with {{skillchance }} to start out with.  It's not a problem to send in an Actor ID and Skill ID and assemble something like "Actor.OJtL5LuzTNzZuP0I.Item.0Cqz54a9ZopcT4YO" and use that to get the skill and then return its chance.

I was thinking we could pass in "itemId (skillId), actorId, tokenId, and sceneId to assemble something like "Scene.wi3CpXCPzSYIAxnT.Token.GX8M1l22ETCvnqry.Item.0Cqz54a9ZopcT4YO", or if sceneId and tokenId are null we would assemble a uuid like above starting with "Actor".

However, if we're dealing with a token that is not linked to the actor, we can't know the Scene ID in the handlebars template ("gear-tab.hbs" in this case).  So we're left with doing basically the same thing, which is looking up a token based only on its id so that we can see if it has a Scene and if so use the "Scene" uuid otherwise use the "Actor" uuid.

Is this even worth doing?  It doesn't avoid the rigamarole we do in getActorFromIds.

**Comment by wake42** [comment]
Foundry provides a uuid getter on all tokens and actors so you don't need to assemble that yourself. Just read from token.uuid.

**Comment by Moonpile** [comment]
I was not able to do something like {{skillchance skill.uuid}} in the handlebars template to pass the uuid into the handlebars helper.

**Comment by wake42** [comment]
I think `{{skillchance` needs two parameters, one for the itemId to search for in the actor since you don't have the embedded skill as an item :
https://github.com/sun-dragon-cult/fvtt-system-rqg/blob/34f7233067ad5e11f45fa61efe3b56cefb0d6a88/src/actors/sheet-parts/gear-tab.hbs#L198
So possibly `{{skillchance skillId @root.uuid}}` could work?
