### ISSUE TITLE
Make it possible to create arbitrarily named passions

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#405]
### _Why:_ Is your feature request related to a problem?
In the RuneQuest system you can invent any passion, but the rqg-system models that as an enum. Make it possible to type in any name for a passion.

### _What:_ Describe the solution you'd like
Make the passion name editable, but give suggestions with the most common passions (currently in the enum).

The name suggestions could be translated and used in a similar way to how the combat maneuver name works.

Currently you get a different item image depending on the selected passion. Having a translated passion name in a regular text field would break this behaviour. To fix this take inspiration from how the combat maneuver is used to select a damage type. If the passion name matches one of the translated suggestions then the matching image is selected, otherwise a default image is set.

**Comment by Moonpile** [comment]
> Currently you get a different item image depending on the selected passion. Having a translated passion name in a regular text field would break this behaviour. To fix this take inspiration from how the combat maneuver is used to select a damage type. If the passion name matches one of the translated suggestions then the matching image is selected, otherwise a default image is set.

Because the image was hard-linked to the chosen Passion Name value chosen, it was not editable.  I think we need to also allow editing the image.  And there should be just a "default" image for any passion that is not one of the suggested ones.  Either way, the user should then be able to then override the image.

Maybe this one could be the default for non-suggested passions with the idea being that it's a passion that has just been added?  https://game-icons.net/1x1/zeromancer/heart-plus.html

**Comment by Moonpile** [comment]
Also Hit Locations have a similar issue in that I can only make ones that are on the drop-down list.  What if I want to make a tail or tentacle?
