### ISSUE TITLE
Opening the elder race sheets from bestiary throws error

### ISSUE THREAD

**Issue by phoenix-pnp** [sun-dragon-cult/fvtt-system-rqg#484]
### _What_: Describe the bug

After importing the bestiary compendium pack, opening Aldryami (Green Elf), Mostali (Dwarf) or Uzko (Dark Troll) throws error:
`Handlebars helper expected item but got Actor called Uzko (Dark Troll)`

### _How:_ To Reproduce

1. Import Bestiary | en compendium pack
2. open any of the above mentioned three charakter sheets from Actors -> Bestiary
3. Sheet opens, accompanied by error message

The error seems not to be related to the brackets, as Horse (Seredae) does not throw an error!

Uzko (Dark Troll) throws the error twice

### Expected behavior

No error message

### Screenshots

![image](https://user-images.githubusercontent.com/18349726/221031362-edff5286-d820-4995-be88-bbf951287831.png)
![image](https://user-images.githubusercontent.com/18349726/221031711-1f896fe5-1c9c-4fac-bd41-ee428f7201cb.png)
![image](https://user-images.githubusercontent.com/18349726/221031745-38a0b443-8c4f-46a3-aa74-d112cda05f33.png)

### Environment - please paste the information from foundry settings tab "support" button:

![image](https://user-images.githubusercontent.com/18349726/221031950-2bdb4ab9-c790-4f9a-b039-43867d1ae2e3.png)

**Comment by Moonpile** [comment]
I encountered this too.  In the case of missile weapons, it's that the ammo is either not linked or not present on the actor.  If you're looking for a short term fix on this, you'll have to import the Actor and then you can right click on the missile weapon to edit it.  Then you can choose the "Projectile" in the "missile" usage group.  

![image](https://user-images.githubusercontent.com/3959760/221036242-dcb5d3da-4144-4a6d-8594-b8b35455ec0b.png)

**Comment by Moonpile** [comment]
The problem with the Large Shield on the Uzko kind of fixes itself after you edit it once, so I'm really not sure what's going on with that one.

**Comment by Moonpile** [comment]
@wake42 The problem is we can't really pre-link the bow's "projectileId" to the arrows id, because the id of the arrows as compiled in the compendium is not the same as the id of the arrows as compiled onto the actor's inventory.  The ids of the actor's inventory items seems to change with every compile.

At least until we do some kind of rqid linking, I think the better solution here is to make a missile weapon that does not have linked ammo have a ⚠ or something like that instead (with a tool-tip explaining what the problem is).  This is something that might happen in play (you buy a bow but forget the arrows or the GM forgets to add the arrows) so it's not really a 🐛.  At least for v2.1.1 the GM will have to link the arrows to the bow, but at least they'll have a clean alert and either a warning or no ui.notification.

**Comment by wake42** [comment]
Yes this is an error that will basically be solved by #154. I agree that a warning icon would be better in this case though. It might need some extending the common error checking function since it's used by multiple handlebars.

I think a tool tip is hard to produce since this is a handlebar that just requests a string to display. To do that I think we would have to move the preparation of that sheet data to the getData function so that you don't need the handlebars helper.
