### ISSUE TITLE
Toggle to Turn off background changes for wounded and dead 

### ISSUE THREAD

**Issue by Lockbox313** [sun-dragon-cult/fvtt-system-rqg#603]
### _Why:_ Is your feature request related to a problem?

The ability to turn off the background changes for dead and wounded as they are highly distracting.  In the case of spirits it makes the sheet nearly unreadable.

**Comment by wake42** [comment]
I had a look at the Ghost and elementals that are included in the system - and they are not affected by the "wounded" effects. Could it be that you have a CON value on your spirit? And / or maybe hit locations.

**Comment by Lockbox313** [comment]
A wound / death effect was added recently.  When current hp is below  thp the sheet is tinted red.  When thp reach 0 the whole sheet is monochrome and the text is blurred.   I had to add a con value to get rid of the blurring.  How exactly are disembodied spirits i.e. ghost and elementals indicated on the sheet as all I see is a checkbox  for creatures

**Comment by Lockbox313** [comment]
It seems to be some weird combination of things that is triggering the death state.  I will play around with it and try nail down whats doing it.

**Comment by Lockbox313** [comment]
As far as I can make I created a new actor and set the unused characteristics to 0 as opposed  to removing  the values.  So I know what to do it in the futures.

**Comment by wake42** [comment]
Sorry for reopening, but I just wanted to figure this out...

Removing the values should be the same thing as setting them to 0. I'm curious as how you get the wounded effect on a spirit, because I don't get that when I create one. I can get the effect if I add CON - that reveals the "Health" section where total hitpoints is visible and if the current hitpoints is lower than total then the sheet-effect is visible. Generally a spirit should not have CON though unless you're building some specail creature.

![Image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/4853677/51eb7dc2-1202-4fae-a9ce-fd2a12452e56) 

![Image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/4853677/a7bd4fa3-2030-4415-a706-eef362dde265)




A separate question is if the "wounded-effects" are actually good or if they maybe should be possible to toggle off with a system setting. Do you have any input on that?

**Comment by Lockbox313** [comment]
I was getting the dead effect rather than the wounded.  As a player I would find the wounded effect very hard on the eyes, but as I will be gming hopefully it won't be an issue.  The eye bleeding red is much like like the new Roll20 color scheme.  

I was never trying to create a spirit with CON.  I zeroed the non spirit stats from a newly created actor and got the dead effect.  I put a value in  CON so that I could set the the current hit points.  Removing values from the non spirit resolved the problem,

[Dead Spirit](https://www.youtube.com/watch?v=K7uPqx9uUpE)

**Comment by wake42** [comment]
Ok then I misremembered - 0 is not the same as "nothing", but at least it's working. I'll close this issue and ask in the beta channel for opinions on the "wounded effects".

**Comment by wake42** [comment]
adressed in #605
