### ISSUE TITLE
A setting change the image displayed when there are no scenes

### ISSUE THREAD

**Issue by Lockbox313** [sun-dragon-cult/fvtt-system-rqg#651]
### _Why:_ Is your feature request related to a problem?

Not a problem but it would be nice to be able to change or disable the image that is displayed when there is no canvas active.  

### _What:_ Describe the solution you'd like

Currently the image is referenced in the rqg.css and there does not  appear to be a setting to change it.

body {
  background-attachment: fixed !important;
  background-size: cover !important;
  background: url("assets/images/ui/sacred-time.webp") no-repeat;
}

### _Options:_ Describe alternatives you've considered

A setting to change the image file

**Comment by wake42** [comment]
Hi,

what is the usecase for this. The way I see it that image is only shown before you have set up anything (any scene). If you have at least one scene you will never see it again.

The way we do it is to have a "landing page scene" with info relevant to the campaign as well as a background image to match. 

If there was a setting to change the default background you would have only that - a different background image, without any functionality since it's not a scene. The default Foundry background is just a blue-grey texture. How would you like it to function?

**Comment by Lockbox313** [comment]
Simply a path in the settings to the image or blank it out for for none.

**Comment by wake42** [comment]
I understand what you want - I just don't understand the why :-)

**Comment by Lockbox313** [comment]
Why is everyone forced to see that one image.  Someone took the time to put that image there and obviously they want that image there, but why are other groups forced to see that image?  As I said in the initial request this was not a bit but deal but for some reason you seem to want make it a big deal.  Now I have found where this buried I can change it or remove it as I see fit. So I will close this request.

**Comment by wake42** [comment]
Sorry if I came out as not wanting to help - that was not my intention. I just wanted to understand why it was a problem.

The reason I'm hesitant to add another setting is that it does not seem like a problem to me. The only time that image is visible is before there is a scene. Do I understand it correctly that you are playing without any scenes?

I'll keep this case closed and you are free to ignore it or answer if you want to help me understand the usecase.
