### ISSUE TITLE
Filling in skills and it lagged really badly

### ISSUE THREAD

**Issue by godfatherbrak** [sun-dragon-cult/fvtt-system-rqg#688]
I had dragged the skills and weapons skills onto the sheet.  Things were working fine for awhile when I was putting in skill %s in the box next to the final percentages.  When I was close to done, the Skills page lagged really badly.  When I restarted, it had the same problem.  The other tabs would work well but Skills would take a long time to register any clicks.

Doing it without pulling all the weapons in seems to have helped on a new character.  I also deleted some of the extra skills with lores, languages, etc.

**Comment by wake42** [comment]
I will have a look, in the mean time would you mind going to Foundry Game Settings -> Support & Issues -> Support Details and "Copy Report to Clipboard" and paste it here.

**Comment by wake42** [comment]
I have tried to reproduce this, but have not been able to. Any further insight to help me find the problem is appreciated since I don't think I'll find this error without further input. Would you mind exporting the actor that is lagging in case there is something in it that has broken.

**Comment by godfatherbrak** [comment]
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: rqg, 3.4.1
Active Modules: 1
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FoundryVirtualTabletop/11.315.0 Chrome/112.0.5615.204 Electron/24.8.5 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

No viewed scene

Actors: 1 | Items: 545 | Journal Entries: 281 | Rollable Tables: 5 |
Playlists: 0 | Compendium Packs: 57 | Chat Messages: 62

**Comment by godfatherbrak** [comment]
I think I found it.  I had dragged the Weapons Skills onto the character and it loaded those in.  That has slowed it down. (Not as bad as the other day, but I had been entering a bunch of skill percentages then.)
[fvtt-Actor-ankka-littlebill-vnhYpwX1K56VvTMV.json](https://github.com/sun-dragon-cult/fvtt-system-rqg/files/13969621/fvtt-Actor-ankka-littlebill-vnhYpwX1K56VvTMV.json)

**Comment by wake42** [comment]
Hi, I noticed that you have every skill available, including all weapon skills. You only need the weapon skills that the actor's weapon uses, and dragging a weapon to an actor will add the required skills automatically.

I would recommend starting building a new character by copying the actor from the wiki module in the folder `Bestiary` / `Adventurers` / `Human (Base)` since that actor contains a base set of skills, runes, hit locations etc. You can then add skills specific to your characters profession like "Library Use" or "Alchemy" (skills that have base chance 0). And drag the weapon items the character should have to the actor so that only the needed weapon skills are added.

That said, I'm still not sure why adding all those weapon skills should slow things down as you describe. I think I need to experiment a bit more to find what's going on.

**Comment by wake42** [comment]
I'm not really sure this issue is fixed, but in release 3.4.2 I've at least improved the speed of generating the data needed for the actorsheet. 

Please update the system and try again to see if the lagging is reduced (also read my previous comment about not adding everything available to the actor).
