### ISSUE TITLE
Adding Compendium entries I have created to the Wiki release

### ISSUE THREAD

**Issue by The-Axel** [sun-dragon-cult/fvtt-system-rqg#694]
I have created a lot of entries (cults, spells, equipment, etc.) from the rulebooks that are not in the current Wiki, and would like to make them available to other players for inclusion in the release.

Would that be helpful?
How could I do that?

**Comment by wake42** [comment]
Only items in the wiki are allowed to be included in the system / wiki module because of copyright reasons. So you can use them for your own games, but are not allowed to share them.

In the future there are plans for foundry modules for the starter set etc, but that will be modules you need to pay for.

If you want you could DM me the entries, and that could maybe make things a little faster for me for entering it into upcoming modules, but I have no time plan for when those could become available unfortunately.

Does that answer your question?

**Comment by The-Axel** [comment]
It does. Thanks.

**Comment by wake42** [comment]
closing the case for now
