### ISSUE TITLE
Entering Other Modifiers on skill rolls

### ISSUE THREAD

**Issue by The-Axel** [sun-dragon-cult/fvtt-system-rqg#712]
### _What_: Describe the bug

Chat Messages - Skill Rolls. My group can only enter one character at a time into the Other Modifiers box. After entering one character, we have to mouse click on the box again before entering another digit.

### _How:_ To Reproduce

Double click on a skill on a character sheet.
Click on the Other Modifiers box.
Enter two digits.

### Expected behavior

It should be possible to enter multiple digits in succession.

**Comment by wake42** [comment]
I've seen this error before, and it's probably a collision with some module. The next major release (3.5.0) will contain a complete rewrite of how rolls are made, and there will no longer be input boxes for modifiers in chat (they will be in a dialog instead). That should avoid this incompatibility altogether, so I'm closing this case as it will be fixed in by another refactor. 

In the meantime, I unfortunately do not remember what module was causing this, so if you want to get it to work now, you would have to do some detective work yourself by deactivating modules (optionally with the help of the module https://foundryvtt.com/packages/find-the-culprit).
