### ISSUE TITLE
Hide "dead" actor health for spirits

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#74]
Spirits currently get a "dead" actor health and a chat that soys something like `Spirit runs out of hitpoints and dies here and now!`

To fix that we need to type hitpoints.max as `number | undefined` and modify the code using it accordingly, setting actor health to "healthy" and handling the undefined value. 

Hide "health" panel if hitpoints.max is undefined - how should an added hitlocation be handled?

**Comment by Moonpile** [comment]
I looked into this a bit and I don't think I fully understand TypeScript typing enough to tackle this.  However I had the following related observations and questions:
- If you have CON 1, SIZ 1, POW 1 the system currently gives you negative max hit points.  Since you need 3 hp to be conscious, is 3 hp the floor for hit points?
- If your current hit points are greater than your max hit points and you close and re-open the actor sheet, it forces your current hp back down to max hp. Vigor should allow you to have greater than max hp, though I think this will work by increasing CON.  Instead of recalculating(?), Vigor adds +3 to total hp and +1 to each location.

**Comment by Moonpile** [comment]
We definitely need to think this through some more.  I think we need a way to say a creature does not have a Characteristic (null).  I suggest we make a GM context menu option to "turn off the characteristic".  Then, when calculating attributes such as hit points, if you have a null in any of the values the attribute depends upon, you would have null in the attribute.

Here's a Spirit I made with zero CON, SIZ, and POW.  I gave it hit locations because you can't see total hit points without hit locations.

![image](https://user-images.githubusercontent.com/3959760/210249928-7b74f1b8-47b9-46d8-8656-5fe8178c78ed.png)

And more realistically here's one with zero CON and SIZ but 15 POW.

![image](https://user-images.githubusercontent.com/3959760/210250395-fbcb5cc4-4360-4a88-8948-5df2b372dc8b.png)

Here's a Tiny thing with CON 1, SIZ 1, and POW 1 that I made, and as you can see it's got negative total hit points out of the box.  I think either the floor for hit points should be 3, or if your total is 3 or less that you're not unconscious or dead until you hit 0.    I'm not even sure what kind of creature we'd be modelling here though.  With stats like those it's basically not a physical threat of any kind.  Like a mouse would at least have more CON and maybe more POW.

![image](https://user-images.githubusercontent.com/3959760/210249994-ec582268-476d-453b-a23d-7516dac2b59c.png)

**Comment by wake42** [comment]
There is already a way to "not have" a characteristic - just delete both the formula and the value like in the Demo Spirit.
![image](https://user-images.githubusercontent.com/4853677/210276946-3ca42b1d-a18f-492a-9e62-98d2fc2aa64c.png)
If an actor does not have CON & SIZ I think it should not have HP either and subsequently not a system.attributes.health. Not sure how to handle death by negative MP though.
The problem now is that you will always get a total HP and with that comes an actor health. 

For actors with really low CON, SIZ & POW that is another question and I'm not sure what RQG says about that - but maybe there should be a minimum total HP of 1 when calculating that in RqgCalculations.hitPoints() Possibly that is the easiest solution. Spirits really should not have HP at all but that is already hidden on the actor sheet so if they get total HP of 1 then the "dead" would not be there either.

**Comment by Moonpile** [comment]
Agreed that discorporate Spirits should not have Hit Points at all.

I didn't know about removing the formula and didn't think of simply deleting the value instead of setting it to zero.  Those work for me to indicate that a creature does not have a characteristic.  

The Spirit does still say "dead" in the upper right corner.  Also, if you drag a spirit out into a scene all is well, but if you make any change to it at all, like it loses Magic Points, it immediately gets the "Dead" status applied to it.  This issue should include fixing that as well.

Freshly dragged out:

![image](https://user-images.githubusercontent.com/3959760/210280050-27e5c045-f40e-4661-88fc-6cb464df4b9b.png)

Lost 5 Magic Points and is now marked dead:

![image](https://user-images.githubusercontent.com/3959760/210280070-737725b4-c403-4f89-95dc-46a588cf62b8.png)

Really it's if you have no CON then you have no Hit Points.  So that calculation ought to check for no value in CON (and also no formula???) and if that's the case set hitPoints.max and hitPoints.value to undefined.  Then I guess we have to see how that affects the status marker.

**Comment by wake42** [comment]
The formula does not really matter for the calculation I think - if you have an unlinked actor and duplicate it / drag it from a compendium, then it will reroll and give a random value. But that is expected I would say since the formula is supposed to work that way.

**Comment by Moonpile** [comment]
Also if hitPoints.value and hitPoints.max are undefined the entire Health section should not render.

So this leaves the question of what to do with creatures that have very low CON (and SIZ and POW).  According to the rules at 1 or 2 hit points you're unconscious but if you have a max HP of 1 or 2 that shouldn't apply in my opinion.  OR there should be a floor of 3 hit points.  

@ChaosiumNeil should probably clarify this bit of logic.  Otherwise, I think I'm good to go with fixing this.

**Comment by wake42** [comment]
That's true, 3 would probably be a good floor value. Go with that I think. The smallest HP I could find in the bestiary was for Nilmergs with 4, but if you roll low on the formulas specified on that you could get -1 HP on that creature...
