### ISSUE TITLE
Max HP & MP after character creation

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#87]
When an actor is created, or after characteristics are regenereated, the HP and MP of the actor should be max. Today it starts as 0 snd you manually have to raise it to the max value.

**Comment by Moonpile** [comment]
You have to have hit locations before you can even see the 
![image](https://user-images.githubusercontent.com/3959760/146676838-6d118c0e-9c30-4aa1-9c89-ead5cdf07149.png) which makes total sense, since if you don't have hit locations I don't think you have general HP either (after looking through the Bestiary a bit).

I also think that if you're at max HP and your CON, SIZ, or POW change then your current HP should change to match max HP.  Not sure what we'd want to happen if your CON, SIZ, or POW change and you are either below or above(?) max HP.
