### ISSUE TITLE
Equipping an item that's in a bag should remove it from the bag.

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#93]
Currently changing the "notCarried, carried, equipped" state of the item is changing the state of the bag it's in and all the other items that are also in the bag, and changing the bag's "notCarried, carried, equipped" state is changing the items.

At the very least equipping an item from a bag implies that it's no longer in the bag.

Might want to consider moving items that are in the bag from their grid to grid items under the bag.

**Comment by wake42** [comment]
Yes I agree - that sounds more natural than the current "change equip status of everything in the bag":
If the item that changing equip status is a container, then change equip status of everything in it.
If it's not then only change that item (and clear the location)

It's also possible to specify "virtual" containers, for example writing "at home" as location makes it possible to group things. Unless one adds a "virtual" equip icon for those as well it will not be possible to change the equip status of all of those at the same time. But that might actually not be a problem...

About moving items in a bag inside - I think that's a bit problematic since I separate physical items into gear, currency, armor etc. There are 2 views of your belongings though with the "View by location" being a hierarchal view of all physical items.
![image](https://user-images.githubusercontent.com/4853677/146692940-78f30a1e-fed5-4650-97da-927240263a68.png)

**Comment by Moonpile** [comment]
Ok, I didn't see view by location and even after I saw your image it took me 20 seconds or so to find it on the actual character sheet.  Is there some way we could make those stand out more as "tabs"?  After I played with this for a minute I created a "home" virtual bag and I realized that's a good way to specify a "kit" that you can equip all at once with one click.

But there's a difference between a "bag" and a "kit".  If you equip a backpack "bag", you're just carrying everything in it, but if you equip your armor "kit" you want to equip everything in the kit and the kit itself is not an actual thing.

I'll put some more thought into this in the next day or two.

**Comment by wake42** [comment]
Closing this issue as won't fix. 

I've experimented with the idea of removing items from a container when you change the equipped status and found it to be a very confusing UX where it's hard to predict what will happen and also hard to undo the changes if you pulled an item out.

I'm keeping the current behavior of changing the equipped status of everything in a bag (including the bag itself) if you change the equipped status of anything in it. To remove an item from it's container you need to clear the location of the item.
